DefaultContentLanguage = "en"
author = "Teng"
baseURL = "https://t1m3ch0.tk"
copyright = "Copyright © 2020–2021"

disqusShortname = "teng-1"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE"
hasCJKLanguage = true
languageCode = "en"
theme = "tokiwa"
title = "Teng's home"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/noto-serif-sc-v7-latin_chinese-simplified-300" 
description = """
""" 
env = "production" # for Google Analytics and DISQUS.
#favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = false # for introducing $KaTEX$
useChineseFonts = true 

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

#[[menu.main]]
#name = "Categories"
#url = "/categories/"
#weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[social]
bilibili = "https://space.bilibili.com/13080392/"
github = "https://github.com/T1m3ch0"
#gitlab = "http://gitlab.com/"
#instagram = "http://example.com/"
mail = "mailto:1457404238@qq.com"
#twitter = "http://twitter.com/"
#weibo = "http://example.com/"
#youtube = "http://youtube.com/"
#zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]
