name = "Diary"
license = "MIT"
licenselink = "https://github.com/amazingrise/hugo-theme-diary/blob/master/LICENSE"
description = "Log time,thoughts,and dreams."
homepage = "https://websec.ga"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "Timecho"
  homepage = "https://websec.ga"
