name = "Diary"
license = "MIT"
licenselink = "https://github.com/amazingrise/hugo-theme-diary/blob/master/LICENSE"
description = "Moments piled up. A simple, elegant blog theme."
homepage = "https://amazingrise.net/"
tags = ["blog"]
features = ["mobile","elegant"]
min_version = "0.59.0"

[author]
  name = "amazingrise"
  homepage = "https://amazingrise.net/"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
